### PR TITLE
fix update workflow

### LINKED ISSUE #12: update workflow is broken
```
. .venv/bin/activate && ./gen_fresh_dirinfo.py generate-dirinfo \
	--authority-signing-key authority-private/authority_signing_key \
	--authority-certificate directory-cache/certificate.txt \
	--consensus directory-cache/consensus.txt \
	--microdescriptors directory-cache/microdescriptors.txt
Traceback (most recent call last):
  File "/home/runner/work/lightarti-directory/lightarti-directory/tools/./gen_fresh_dirinfo.py", line 912, in generate_customized_consensus
    vote_mtbf.validate_signatures(key_cert_mtbf)
  File "/home/runner/work/lightarti-directory/lightarti-directory/tools/.venv/lib/python3.9/site-packages/stem/descriptor/networkstatus.py", line 1307, in validate_signatures
    raise ValueError('Network Status Document has %i valid signatures out of %i total, needed %i' % (valid_digests, total_digests, required_digests))
ValueError: Network Status Document has 0 valid signatures out of 0 total, needed 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/lightarti-directory/lightarti-directory/tools/./gen_fresh_dirinfo.py", line 1217, in <module>
    main(sys.argv[0], sys.argv[1:])
  File "/home/runner/work/lightarti-directory/lightarti-directory/tools/./gen_fresh_dirinfo.py", line 1206, in main
    namespace.callback(namespace)
  File "/home/runner/work/lightarti-directory/lightarti-directory/tools/./gen_fresh_dirinfo.py", line 1012, in generate_customized_consensus_cb
    generate_customized_consensus(
  File "/home/runner/work/lightarti-directory/lightarti-directory/tools/./gen_fresh_dirinfo.py", line 914, in generate_customized_consensus
    raise InvalidVote(str(err))
__main__.InvalidVote: Network Status Document has 0 valid signatures out of 0 total, needed 0
make[1]: *** [Makefile:43: directory-cache/certificate.txt] Error 1
make: *** [Makefile:78: update_cache_churn] Error 2
make[1]: Leaving directory '/home/runner/work/lightarti-directory/lightarti-directory/tools'
```

blocking https://github.com/c4dt/lightarti-rest/issues/116

### PR DESCRIPTION
**Pull request by PascalinDe**
This PR

* points to the C4DT's fork of stem which includes fixes that may be included more slowly (or not at all) in upstream
* adds tolerance of  missing/mismatching microdescriptors by skipping the routers/microdescriptors in question

Still needs to be done:

* [ ] add test cases

### CODE REVIEW

**Comment by ineiti** [comment]
I'm just trying to run it on my Mac with:

```
DIR_AUTH_PASSWORD=1234 gmake cache
```

but it fails with 

```
FileNotFoundError: [Errno 2] No such file or directory: 'tor-gencert'
```

Is that normal behaviour?

**Comment by ineiti** [comment]
Also:
- linter should run successfully
- once it's ready for review, you can click `Ready for review`

**Comment by PascalinDe** [comment]
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'tor-gencert'
> ```
> 
> Is that normal behaviour?

`tor-gencert` is a command that has been installed by the tor package on my system I believe

`tor` is part of the requirements maybe you can install it and try again?

**Comment by ineiti** [comment]
OK, makes sense. Now I get the following:

```
ValueError: Network Status Document has 0 valid signatures out of 0 total, needed 0
```

**Review by ineiti — APPROVED** [review]
Except that I cannot run it on my computer, it looks fine.

**Comment by PascalinDe** [comment]
> Except that I cannot run it on my computer, it looks fine.

have you tried `make authority` before running `make update_cache`?

**Pull request merged**
