### PR TITLE
Move `tools` from `lightarti-rest`

### PR DESCRIPTION
**Pull request by cgrigis**

### CODE REVIEW

**Comment by cgrigis** [comment]
To be confirmed at the next generation if it works properly

**Review by ineiti — APPROVED** [review]
To test the workflow, you can add an `on: push` to `workflows/update.yaml`, and temporally comment out the release action, or change the release tag to some `test` tag.

I don't understand anymore how it worked before with regard to the checkout of `lightarti-rest`, and then why the `cd tools` in the `fetch_tor_dir` step works. So I'd just make sure that it still works here.

**Comment by cgrigis** [comment]
> I don't understand anymore how it worked before with regard to the checkout of `lightarti-rest`, and then why the `cd tools` in the `fetch_tor_dir` step works. So I'd just make sure that it still works here.

My understanding by looking at the logs of a past run is that the second checkout was "cancelling" the first one, and we ended up with a plain checkout of `lightarti-rest`, along with a `tools` directory.

**Comment by cgrigis** [comment]
> To test the workflow, you can add an `on: push` to `workflows/update.yaml`, and temporally comment out the release action, or change the release tag to some `test` tag.

I used `on: workflow_dispatch` to allow manual trigger, and it looks like it is working.

**Comment by ineiti** [comment]
> on: workflow_dispatch

Wow - this is very nice!

**Pull request merged**
